### ISSUE TITLE
Issue starting the travel

### ISSUE THREAD

**Issue by liz3** [CrushedPixel/PixelCamMod#22]
Hey there,
i just installed the mod and wanted to play a littlebit around, bu i didnt came far.
In game on the command `/cam start 30` i just got an internal error bla.
But as im a dev my self i looked into the log and he throws an IllegalArgumentException.
Here the whole Exception: 
`[21:59:47] [Client thread/WARN]: Couldn't process command: 'cam start 60'
java.lang.IllegalArgumentException: Invalid format: "60"
	at org.joda.time.format.PeriodFormatter.parseMutablePeriod(PeriodFormatter.java:330) ~[PeriodFormatter.class:?]
	at org.joda.time.format.PeriodFormatter.parsePeriod(PeriodFormatter.java:308) ~[PeriodFormatter.class:?]
	at com.replaymod.pixelcam.command.CamCommand.start(CamCommand.java:189) ~[CamCommand.class:?]
	at com.replaymod.pixelcam.command.CamCommand.func_184881_a(CamCommand.java:109) ~[CamCommand.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:103) [k.class:?]
	at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:92) [ClientCommandHandler.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:437) [bft.class:?]
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:428) [bft.class:?]
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81) [bew.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:571) [bft.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:525) [bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
`
I tried several things like: 30.0(in case it would be a double, or i dont know :D).

Can someone help me?

**Comment by paolobarbolini** [comment]
The correct way to use the cam start command is to write the number followed by the unit of measure.
For example if you want the travel to last 30 seconds you would use ``/cam start 30s``
The other accepted units of measure are minutes (for example ``/cam start 5min``) and hours (for example ``/cam start 2h``).
Hope it helps.

**Comment by liz3** [comment]
Yes, i just saw a video of it :D
